model_name: "p-prodec2-modular-4SAT-pytorch"
model_type: "np-nd-np"
version: "5.0g"
has_meta_data: false # true
train_path: ["../../datasets/SAT/p-cnf-3-10-large.json"]
validation_path: ["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"]
test_path: ["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"] #["../../datasets/SAT/M-4SAT-validation-2/M-4SAT-validation-2_0_7.0_10.0.json"] #["../../datasets/SAT/M0-4SAT-100"] #["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/sat-race-test.json"] # ["../../datasets/SAT/cnf-10.json"] #["../../datasets/SAT/3SAT-100"] #
model_path: "../../Trained-models/SAT"
repetition_num: 1
train_epoch_size: 40000
epoch_num: 500
label_dim: 1
edge_feature_dim: 1
meta_feature_dim: 0 # 1
error_dim: 3
metric_index: 0
prediction_dim: 1
hidden_dim: 150  # 110
mem_hidden_dim: 100
agg_hidden_dim: 100  # 135
mem_agg_hidden_dim: 50  # 50
classifier_dim: 50  # 100
batch_size: 5000
learning_rate: 0.00001 # 0.0001
exploration: 0.05 # 0.1
verbose: true
randomized: true
train_inner_recurrence_num: 1
train_outer_recurrence_num: 10
test_recurrence_num: 20
max_cache_size: 100000
dropout: 0.2
clip_norm: 0.65
weight_decay: 0.0000000001
loss_sharpness: 5
train_batch_limit: 4000000
test_batch_limit: 40000000
generator: "modular"
min_n: 5
max_n: 100
min_alpha: 5
max_alpha: 10
min_k: 4
min_q: 0.8
max_q: 0.9
min_c: 10
max_c: 20
local_search_iteration: 0
epsilon: 0.5
lambda: 1
